// Vietnam provinces data for dropdown selection
export const VIETNAM_PROVINCES = [
  { code: '01', name: 'Thành phố Hà Nội' },
  { code: '02', name: 'Tỉnh Hà Giang' },
  { code: '04', name: 'Tỉnh Cao Bằng' },
  { code: '06', name: 'Tỉnh Bắc Kạn' },
  { code: '08', name: 'Tỉnh Tuyên Quang' },
  { code: '10', name: 'Tỉnh Lào Cai' },
  { code: '11', name: 'Tỉnh Điện Biên' },
  { code: '12', name: 'Tỉnh Lai Châu' },
  { code: '14', name: 'Tỉnh Sơn La' },
  { code: '15', name: 'Tỉnh Yên Bái' },
  { code: '17', name: 'Tỉnh Thái Nguyên' },
  { code: '19', name: 'Tỉnh Lạng Sơn' },
  { code: '20', name: 'Tỉnh Quảng Ninh' },
  { code: '22', name: 'Tỉnh Bắc Giang' },
  { code: '24', name: 'Tỉnh Phú Thọ' },
  { code: '25', name: 'Tỉnh Vĩnh Phúc' },
  { code: '26', name: 'Tỉnh Bắc Ninh' },
  { code: '27', name: 'Tỉnh Hải Dương' },
  { code: '30', name: 'Thành phố Hải Phòng' },
  { code: '31', name: 'Tỉnh Hưng Yên' },
  { code: '33', name: 'Tỉnh Thái Bình' },
  { code: '34', name: 'Tỉnh Nam Định' },
  { code: '35', name: 'Tỉnh Ninh Bình' },
  { code: '36', name: 'Tỉnh Thanh Hóa' },
  { code: '37', name: 'Tỉnh Nghệ An' },
  { code: '38', name: 'Tỉnh Hà Tĩnh' },
  { code: '40', name: 'Tỉnh Quảng Bình' },
  { code: '42', name: 'Tỉnh Quảng Trị' },
  { code: '44', name: 'Tỉnh Thừa Thiên Huế' },
  { code: '45', name: 'Thành phố Đà Nẵng' },
  { code: '46', name: 'Tỉnh Quảng Nam' },
  { code: '48', name: 'Tỉnh Quảng Ngãi' },
  { code: '49', name: 'Tỉnh Bình Định' },
  { code: '51', name: 'Tỉnh Phú Yên' },
  { code: '52', name: 'Tỉnh Khánh Hòa' },
  { code: '54', name: 'Tỉnh Ninh Thuận' },
  { code: '56', name: 'Tỉnh Bình Thuận' },
  { code: '58', name: 'Tỉnh Kon Tum' },
  { code: '60', name: 'Tỉnh Gia Lai' },
  { code: '62', name: 'Tỉnh Đắk Lắk' },
  { code: '64', name: 'Tỉnh Đắk Nông' },
  { code: '66', name: 'Tỉnh Lâm Đồng' },
  { code: '67', name: 'Tỉnh Bình Phước' },
  { code: '68', name: 'Tỉnh Tây Ninh' },
  { code: '69', name: 'Tỉnh Bình Dương' },
  { code: '70', name: 'Tỉnh Đồng Nai' },
  { code: '72', name: 'Tỉnh Bà Rịa - Vũng Tàu' },
  { code: '74', name: 'Thành phố Hồ Chí Minh' },
  { code: '75', name: 'Tỉnh Long An' },
  { code: '77', name: 'Tỉnh Tiền Giang' },
  { code: '79', name: 'Tỉnh Bến Tre' },
  { code: '80', name: 'Tỉnh Trà Vinh' },
  { code: '82', name: 'Tỉnh Vĩnh Long' },
  { code: '83', name: 'Tỉnh Đồng Tháp' },
  { code: '84', name: 'Tỉnh An Giang' },
  { code: '86', name: 'Tỉnh Kiên Giang' },
  { code: '87', name: 'Thành phố Cần Thơ' },
  { code: '89', name: 'Tỉnh Hậu Giang' },
  { code: '91', name: 'Tỉnh Sóc Trăng' },
  { code: '92', name: 'Tỉnh Bạc Liêu' },
  { code: '93', name: 'Tỉnh Cà Mau' },
];

export type Province = typeof VIETNAM_PROVINCES[number];

